# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef0448d55d821485c2ece8dfd2693cf51fbe7e1db9f3109e41e88c374d1c5b1c15f40edd0e80d53930c3b62b30489ab707e79f3d6672999ff8eea7b3688caffc

test:
  secret_key_base: a36a23460d335c6ef4823f04f3542f80a95dfa5c451e7523732995708b308c9dd48e29341dc7d136dbd5dce555e7ca0aa9ba2d39618e4735d8383c50524ba6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
